<%@ Page Title="" Language="C#" MasterPageFile="~/portal.Master" AutoEventWireup="true" CodeBehind="user-universities.aspx.cs" Inherits="WebApplication1.user_universities" %>



<asp:Content ID="Content3" ContentPlaceHolderID="navPlace" runat="server">
    <li>
        <a href="myPortal.aspx">
            <i class="fa fa-home" aria-hidden="true"></i>
            <p>Home</p>
        </a>
    </li>
    <li class="active">
        <a href="user-universities.aspx">
            <i class="fa fa-university" aria-hidden="true"></i>
            <p>Universities</p>
        </a>
    </li>
    <li>
        <a href="UserPrepare.aspx">
            <i class="fa fa-book" aria-hidden="true"></i>

            <p>Prepare</p>
        </a>
    </li>
  
     <li>
        <a href="Chat.aspx">
            <i class="fa fa-comments-o" aria-hidden="true"></i>
            <p>Career Counseling</p>
        </a>
    </li>

</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <style>
        .button {
            display: inline-block;
            background-color: #e6a303;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 15px;
            font-family: 'Roboto';
            font-weight: 700;
            padding: 10px;
            width: 200px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 5px;
        }

            .button span {
                cursor: pointer;
                display: inline-block;
                position: relative;
                transition: 0.5s;
            }

                .button span:after {
                    content: '\00bb';
                    position: absolute;
                    opacity: 0;
                    top: 0;
                    right: -20px;
                    transition: 0.5s;
                }

            .button:hover span {
                padding-right: 25px;
            }

        .ab {
            color: white !important;
        }

        .button:hover span:after {
            opacity: 1;
            right: 0;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

    <div class="content">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <h4 id="ab" runat="server"></h4>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <a href="universities.aspx" class="ab button"><span>Add a University</span></a>
                        </div>
                        <div class="header">
                            <h4 class="title">Universities applied for</h4>

                        </div>
                        <div class="content table-responsive table-full-width">
                         <asp:GridView ID="universitiesGrid" runat="server" DataKeyNames="entery_id" OnRowDeleting="deleteUni" OnRowDataBound="universitiesGrid_RowDataBound" EmptyDataText="No Universities Have Been Added Yet." AutoGenerateDeleteButton="True" CssClass="table table-hover"> </asp:GridView>
                       </div> 
                           
                    </div>
                </div>




            </div>



        </div>
    </div>
</asp:Content>

